#! /bin/bash
set -eu

DIR="$(dirname "$0")"

# Install for Vim.
mkdir -p "${HOME}/.vim"
cp -raf "${DIR}/ftdetect" "${DIR}/ftplugin" "${DIR}/syntax" "${HOME}/.vim/"

# Install for Neovim.
mkdir -p "${HOME}/.config/nvim"
cp -raf "${DIR}/ftdetect" "${DIR}/ftplugin" "${DIR}/syntax" "${HOME}/.config/nvim/"

echo "Done."
