#!/bin/bash

# SPDX-FileCopyrightText: 2022 - 2025 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

DIR="$(dirname "$0")"

function install_vim {
  mkdir -p "${HOME}/.vim"
  cp -rafv "${DIR}"/{ftdetect,ftplugin,syntax} "${HOME}"/.vim/
}

function install_neovim {
  mkdir -p "${HOME}/.config/nvim"
  cp -rafv "${DIR}"/{ftdetect,ftplugin,syntax} "${HOME}"/.config/nvim/
}

function print_usage {
  cat << EOF
./install usage:
  -v|--vim         install Vim files
  -n|--neovim      install Neovim files
  -h|--help        print this message
EOF
}

OPTIONS=vnh
LONGOPTIONS=vim,neovim,help
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "${0}" -- "${@}")
eval set -- "${PARSED}"

if [ ${#} -eq 1 ]; then
  install_vim
  install_neovim
fi

while [ ${#} -ge 1 ]; do
  case ${1} in
    -v|--vim)
      install_vim
      shift
      ;;
    -n|--neovim)
      install_neovim
      shift
      ;;
    -h|--help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "ERROR: invalid flag ${1@Q}."
      exit 3
      ;;
  esac
done

echo "Done."
