#! /bin/bash
set -eu

rm_file() {
  if [ -f "${1}" ]; then
    rm -v "${1}"
  fi
}

rm_dir() {
  if [ -d "${1}" ]; then
    rmdir --ignore-fail-on-non-empty "${1}" || true
  fi
}

rm_file "${HOME}/.vim/ftdetect/kitty.vim"
rm_file "${HOME}/.vim/ftplugin/kitty.vim"
rm_file "${HOME}/.vim/syntax/kitty.vim"
rm_file "${HOME}/.vim/syntax/kitty-session.vim"

rm_dir "${HOME}/.vim/ftdetect/"
rm_dir "${HOME}/.vim/ftplugin/"
rm_dir "${HOME}/.vim/syntax/"

rm_file "${HOME}/.config/nvim/ftdetect/kitty.vim"
rm_file "${HOME}/.config/nvim/ftplugin/kitty.vim"
rm_file "${HOME}/.config/nvim/syntax/kitty.vim"
rm_file "${HOME}/.config/nvim/syntax/kitty-session.vim"

rm_dir "${HOME}/.config/nvim/ftdetect/"
rm_dir "${HOME}/.config/nvim/ftplugin/"
rm_dir "${HOME}/.config/nvim/syntax/"

echo "Done."
