#!/bin/bash

# SPDX-FileCopyrightText: 2022 - 2023 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

function rm_file {
  if [ -f "${1}" ]; then
    rm -v "${1}"
  fi
}

function rm_dir {
  if [ -d "${1}" ]; then
    rmdir -p --ignore-fail-on-non-empty "${1}" || true
  fi
}

function uninstall_vim {
  local vimdir="${HOME}/.vim"

  rm_file "${vimdir}/ftdetect/kitty.vim"
  rm_file "${vimdir}/ftplugin/kitty.vim"
  rm_file "${vimdir}/syntax/kitty.vim"
  rm_file "${vimdir}/syntax/kitty-session.vim"

  rm_dir "${vimdir}/ftdetect/"
  rm_dir "${vimdir}/ftplugin/"
  rm_dir "${vimdir}/syntax/"
}

function uninstall_neovim {
  local nvimdir="${HOME}/.config/nvim"

  rm_file "${nvimdir}/ftdetect/kitty.vim"
  rm_file "${nvimdir}/ftplugin/kitty.vim"
  rm_file "${nvimdir}/syntax/kitty.vim"
  rm_file "${nvimdir}/syntax/kitty-session.vim"

  rm_dir "${nvimdir}/ftdetect/"
  rm_dir "${nvimdir}/ftplugin/"
  rm_dir "${nvimdir}/syntax/"
}

function print_usage {
  cat << EOF
./uninstall usage:
  -v|--vim         uninstall Vim files
  -n|--neovim      uninstall Neovim files
  -h|--help        print this message
EOF
}

OPTIONS=vnh
LONGOPTIONS=vim,neovim,help
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "${0}" -- "${@}")
eval set -- "${PARSED}"

if [ ${#} -eq 1 ]; then
  uninstall_vim
  uninstall_neovim
fi

while [ ${#} -ge 1 ]; do
  case ${1} in
    -v|--vim)
      uninstall_vim
      shift
      ;;
    -n|--neovim)
      uninstall_neovim
      shift
      ;;
    -h|--help)
      print_usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "ERROR: invalid flag ${1@Q}."
      exit 3
      ;;
  esac
done

echo "Done."
